site_name: Escoop Docs
nav:
  - Home: index.md
repo_url: https://github.com/EscoopPL/Docs
site_description: Escoop Documentation
copyright: Licensed Under MIT License
site_author: DDAN
theme:
  name: mkdocs
